### PR TITLE
New post style

### PR DESCRIPTION
**Pull request by triszt4n**
### What's new: :art: 
* Style post page (css in markdown.css, there were no plugins to make markdown html code fancy with css automatically)
* Migrate chakra-ui from v0 to v1
* Replace prismjs plugin to vscode plugin (for code blocks in markdown)
* Add emoji compilation
* Add some plugins for external links and header autolinking
* Tidy up some of the packages used in project
* Replace SFCs with FCs in post and page templates

### CODE REVIEW

**Comment by triszt4n** [comment]
Closes #20 

Bumped to gatsby v3.3 (the plugins too, they all are compatible with v3 right now).
This PR had all the used plugins, so I included this solution for the issue in this PR.

**Comment by OmTheTurtle** [comment]
I'm not sure who can access the netlify settings, maybe @balintkiraly could help bump the node / yarn versions.

**Comment by balintkiraly** [comment]
I changed the version on the UI. But you can create a `.node-version` or `.nvmrc` file with the version number in the root folder of the project. This will be used by the Netlify and it will be useful even for the developers also.

**Review by balintkiraly — APPROVED** [review]

**Review by OmTheTurtle — APPROVED** [review]
:ok_hand:

**Pull request merged**
